import type {
  EmployeeProfile,
  ColleagueProfile,
  OrgChartNode,
  EmploymentHistoryEntry,
  DocumentType,
  Gender,
  MaritalStatus,
  Relationship,
} from "@/types/employee";

export const GENDER_OPTIONS: { value: Gender; label: string }[] = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
  { value: "prefer-not-to-say", label: "Prefer not to say" },
];

export const MARITAL_STATUS_OPTIONS: { value: MaritalStatus; label: string }[] = [
  { value: "single", label: "Single" },
  { value: "married", label: "Married" },
  { value: "divorced", label: "Divorced" },
  { value: "widowed", label: "Widowed" },
];

export const RELATIONSHIP_OPTIONS: { value: Relationship; label: string }[] = [
  { value: "spouse", label: "Spouse" },
  { value: "child", label: "Child" },
  { value: "parent", label: "Parent" },
  { value: "sibling", label: "Sibling" },
  { value: "other", label: "Other" },
];

export const DOCUMENT_TYPE_OPTIONS: { value: DocumentType; label: string }[] = [
  { value: "school-cert", label: "School Certificate" },
  { value: "birth-certificate", label: "Birth Certificate" },
  { value: "passport", label: "International Passport" },
  { value: "national-id", label: "National ID Card" },
  { value: "drivers-license", label: "Driver's License" },
  { value: "marriage-cert", label: "Marriage Certificate" },
  { value: "offer-letter", label: "Offer Letter" },
  { value: "other", label: "Other Document" },
];

export const MOCK_EMPLOYEE_PROFILE: EmployeeProfile = {
  id: "emp-001",
  profilePhoto: "",
  profileCompletion: 85,
  basicDetails: {
    firstName: "Adebayo",
    lastName: "Ogunlesi",
    middleName: "Chukwuemeka",
    dateOfBirth: "1992-06-15",
    gender: "male",
    maritalStatus: "married",
    nationality: "Nigerian",
    stateOfOrigin: "Lagos",
    nin: "12345678901",
    taxId: "TIN-1234567890",
    pensionId: "PEN-NG-00123456",
    bvn: "22345678901",
  },
  contactInfo: {
    personalEmail: "adebayo.ogunlesi@gmail.com",
    workEmail: "adebayo.ogunlesi@sabihr.com",
    phone: "+2348012345678",
    alternatePhone: "+2349087654321",
    address: "15 Admiralty Way, Lekki Phase 1",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
  },
  emergencyContacts: [
    {
      id: "ec-1",
      name: "Ngozi Ogunlesi",
      relationship: "Spouse",
      phone: "+2348098765432",
      email: "ngozi.ogunlesi@gmail.com",
      address: "15 Admiralty Way, Lekki Phase 1, Lagos",
    },
    {
      id: "ec-2",
      name: "Chief Olumide Ogunlesi",
      relationship: "Father",
      phone: "+2348023456789",
      email: "olumide.ogunlesi@yahoo.com",
      address: "22 Ikoyi Crescent, Ikoyi, Lagos",
    },
  ],
  familyDependents: [
    {
      id: "fd-1",
      name: "Ngozi Ogunlesi",
      relationship: "spouse",
      dateOfBirth: "1994-03-22",
      gender: "female",
    },
    {
      id: "fd-2",
      name: "Tunde Ogunlesi",
      relationship: "child",
      dateOfBirth: "2020-11-08",
      gender: "male",
    },
  ],
  documents: [
    {
      id: "doc-1",
      type: "passport",
      name: "International Passport",
      fileName: "passport_adebayo.pdf",
      uploadDate: "2025-08-15",
      expiryDate: "2026-04-20",
      status: "verified",
    },
    {
      id: "doc-2",
      type: "school-cert",
      name: "B.Sc. Certificate",
      fileName: "bsc_certificate.pdf",
      uploadDate: "2025-08-15",
      expiryDate: "",
      status: "verified",
    },
    {
      id: "doc-3",
      type: "national-id",
      name: "NIN Slip",
      fileName: "nin_slip.pdf",
      uploadDate: "2025-09-01",
      expiryDate: "2026-09-01",
      status: "uploaded",
    },
  ],
  employment: {
    employeeId: "SHR-2025-001",
    jobTitle: "Senior Software Engineer",
    role: "Technical Lead",
    department: "Engineering",
    division: "Product Development",
    supervisor: "Chiamaka Eze",
    supervisorTitle: "VP of Engineering",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2025-03-01",
    tenure: "11 months",
    workLocation: "Lagos Office",
    branch: "Head Office - Victoria Island",
    payGrade: "Grade 7",
    contractEndDate: null,
    contractType: "permanent",
    contractDocument: null,
    probationEndDate: "2025-09-01",
    isProbation: false,
  },
};

export const MOCK_COLLEAGUES: ColleagueProfile[] = [
  {
    id: "emp-002",
    name: "Chiamaka Eze",
    jobTitle: "VP of Engineering",
    department: "Engineering",
    email: "chiamaka.eze@sabihr.com",
    phone: "+2348034567890",
    photo: "",
    location: "Lagos Office",
  },
  {
    id: "emp-003",
    name: "Oluwaseun Afolabi",
    jobTitle: "Product Designer",
    department: "Engineering",
    email: "seun.afolabi@sabihr.com",
    phone: "+2348045678901",
    photo: "",
    location: "Lagos Office",
  },
  {
    id: "emp-004",
    name: "Fatima Abdullahi",
    jobTitle: "HR Manager",
    department: "Human Resources",
    email: "fatima.abdullahi@sabihr.com",
    phone: "+2348056789012",
    photo: "",
    location: "Abuja Office",
  },
  {
    id: "emp-005",
    name: "Emeka Okafor",
    jobTitle: "Sales Executive",
    department: "Sales",
    email: "emeka.okafor@sabihr.com",
    phone: "+2348067890123",
    photo: "",
    location: "Lagos Office",
  },
  {
    id: "emp-006",
    name: "Aisha Mohammed",
    jobTitle: "Finance Analyst",
    department: "Finance",
    email: "aisha.mohammed@sabihr.com",
    phone: "+2348078901234",
    photo: "",
    location: "Abuja Office",
  },
  {
    id: "emp-007",
    name: "Tochukwu Nwankwo",
    jobTitle: "Backend Developer",
    department: "Engineering",
    email: "tochukwu.nwankwo@sabihr.com",
    phone: "+2348089012345",
    photo: "",
    location: "Lagos Office",
  },
  {
    id: "emp-008",
    name: "Bukola Adeyemi",
    jobTitle: "Marketing Manager",
    department: "Marketing",
    email: "bukola.adeyemi@sabihr.com",
    phone: "+2348090123456",
    photo: "",
    location: "Lagos Office",
  },
  {
    id: "emp-009",
    name: "Ibrahim Musa",
    jobTitle: "Operations Lead",
    department: "Operations",
    email: "ibrahim.musa@sabihr.com",
    phone: "+2348001234567",
    photo: "",
    location: "Kano Office",
  },
  {
    id: "emp-010",
    name: "Yetunde Bakare",
    jobTitle: "Legal Counsel",
    department: "Legal",
    email: "yetunde.bakare@sabihr.com",
    phone: "+2348012345670",
    photo: "",
    location: "Lagos Office",
  },
];

export const MOCK_ORG_CHART: OrgChartNode = {
  id: "org-1",
  name: "Olufunke Adeyemi",
  title: "CEO",
  department: "Executive",
  photo: "",
  children: [
    {
      id: "org-2",
      name: "Chiamaka Eze",
      title: "VP of Engineering",
      department: "Engineering",
      photo: "",
      children: [
        {
          id: "org-3",
          name: "Adebayo Ogunlesi",
          title: "Senior Software Engineer",
          department: "Engineering",
          photo: "",
          children: [],
        },
        {
          id: "org-4",
          name: "Tochukwu Nwankwo",
          title: "Backend Developer",
          department: "Engineering",
          photo: "",
          children: [],
        },
        {
          id: "org-5",
          name: "Oluwaseun Afolabi",
          title: "Product Designer",
          department: "Engineering",
          photo: "",
          children: [],
        },
      ],
    },
    {
      id: "org-6",
      name: "Fatima Abdullahi",
      title: "HR Manager",
      department: "Human Resources",
      photo: "",
      children: [],
    },
    {
      id: "org-7",
      name: "Bukola Adeyemi",
      title: "Marketing Manager",
      department: "Marketing",
      photo: "",
      children: [],
    },
  ],
};

export const MOCK_EMPLOYMENT_HISTORY: EmploymentHistoryEntry[] = [
  {
    id: "hist-1",
    title: "Software Engineer",
    department: "Engineering",
    startDate: "2025-03-01",
    endDate: "2025-09-01",
    type: "hire",
  },
  {
    id: "hist-2",
    title: "Senior Software Engineer",
    department: "Engineering",
    startDate: "2025-09-01",
    endDate: null,
    type: "promotion",
  },
];

export const UPCOMING_EVENTS = [
  {
    id: "evt-1",
    title: "Annual Leave Balance",
    description: "15 days remaining out of 20",
    date: "2026-12-31",
    type: "info" as const,
  },
  {
    id: "evt-2",
    title: "Public Holiday — Workers' Day",
    description: "Office closed",
    date: "2026-05-01",
    type: "info" as const,
  },
  {
    id: "evt-3",
    title: "Performance Review",
    description: "Mid-year review with your manager",
    date: "2026-03-15",
    type: "warning" as const,
  },
];
