import type { EmploymentStatus, EmploymentType } from "@/types/employee";

export interface EmployeeListItem {
  id: string;
  employeeId: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  photo: string;
  jobTitle: string;
  department: string;
  location: string;
  employmentType: EmploymentType;
  employmentStatus: EmploymentStatus;
  startDate: string;
  supervisor: string;
}

export const EMPLOYEE_STATUS_STYLES: Record<
  EmploymentStatus,
  { label: string; bg: string; color: string }
> = {
  active: {
    label: "Active",
    bg: "bg-emerald-50 border-emerald-200",
    color: "text-emerald-700",
  },
  inactive: {
    label: "Inactive",
    bg: "bg-gray-50 border-gray-200",
    color: "text-gray-700",
  },
  "on-leave": {
    label: "On Leave",
    bg: "bg-amber-50 border-amber-200",
    color: "text-amber-700",
  },
  suspended: {
    label: "Suspended",
    bg: "bg-red-50 border-red-200",
    color: "text-red-700",
  },
  terminated: {
    label: "Terminated",
    bg: "bg-gray-100 border-gray-300",
    color: "text-gray-600",
  },
};

export const EMPLOYMENT_TYPE_LABELS: Record<EmploymentType, string> = {
  "full-time": "Full-time",
  "part-time": "Part-time",
  contract: "Contract",
  intern: "Intern",
};

export const MOCK_EMPLOYEE_LIST: EmployeeListItem[] = [
  {
    id: "emp-001",
    employeeId: "SHR-2025-001",
    firstName: "Adebayo",
    lastName: "Ogunlesi",
    email: "adebayo.ogunlesi@sabihr.com",
    phone: "+2348012345678",
    photo: "",
    jobTitle: "Senior Software Engineer",
    department: "Engineering",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2025-03-01",
    supervisor: "Chiamaka Eze",
  },
  {
    id: "emp-002",
    employeeId: "SHR-2025-002",
    firstName: "Chiamaka",
    lastName: "Eze",
    email: "chiamaka.eze@sabihr.com",
    phone: "+2348034567890",
    photo: "",
    jobTitle: "VP of Engineering",
    department: "Engineering",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2024-06-15",
    supervisor: "Olufunke Adeyemi",
  },
  {
    id: "emp-003",
    employeeId: "SHR-2025-003",
    firstName: "Oluwaseun",
    lastName: "Afolabi",
    email: "seun.afolabi@sabihr.com",
    phone: "+2348045678901",
    photo: "",
    jobTitle: "Product Designer",
    department: "Engineering",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2025-01-10",
    supervisor: "Chiamaka Eze",
  },
  {
    id: "emp-004",
    employeeId: "SHR-2025-004",
    firstName: "Fatima",
    lastName: "Abdullahi",
    email: "fatima.abdullahi@sabihr.com",
    phone: "+2348056789012",
    photo: "",
    jobTitle: "HR Manager",
    department: "Human Resources",
    location: "Abuja Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2024-09-01",
    supervisor: "Olufunke Adeyemi",
  },
  {
    id: "emp-005",
    employeeId: "SHR-2025-005",
    firstName: "Emeka",
    lastName: "Okafor",
    email: "emeka.okafor@sabihr.com",
    phone: "+2348067890123",
    photo: "",
    jobTitle: "Sales Executive",
    department: "Sales",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2025-02-01",
    supervisor: "Ngozi Ibe",
  },
  {
    id: "emp-006",
    employeeId: "SHR-2025-006",
    firstName: "Aisha",
    lastName: "Mohammed",
    email: "aisha.mohammed@sabihr.com",
    phone: "+2348078901234",
    photo: "",
    jobTitle: "Finance Analyst",
    department: "Finance",
    location: "Abuja Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2025-04-15",
    supervisor: "Chibueze Okoro",
  },
  {
    id: "emp-007",
    employeeId: "SHR-2025-007",
    firstName: "Tochukwu",
    lastName: "Nwankwo",
    email: "tochukwu.nwankwo@sabihr.com",
    phone: "+2348089012345",
    photo: "",
    jobTitle: "Backend Developer",
    department: "Engineering",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2025-05-01",
    supervisor: "Adebayo Ogunlesi",
  },
  {
    id: "emp-008",
    employeeId: "SHR-2025-008",
    firstName: "Bukola",
    lastName: "Adeyemi",
    email: "bukola.adeyemi@sabihr.com",
    phone: "+2348090123456",
    photo: "",
    jobTitle: "Marketing Manager",
    department: "Marketing",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2024-11-01",
    supervisor: "Olufunke Adeyemi",
  },
  {
    id: "emp-009",
    employeeId: "SHR-2025-009",
    firstName: "Ibrahim",
    lastName: "Musa",
    email: "ibrahim.musa@sabihr.com",
    phone: "+2348001234567",
    photo: "",
    jobTitle: "Operations Lead",
    department: "Operations",
    location: "Kano Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2024-08-15",
    supervisor: "Olufunke Adeyemi",
  },
  {
    id: "emp-010",
    employeeId: "SHR-2025-010",
    firstName: "Yetunde",
    lastName: "Bakare",
    email: "yetunde.bakare@sabihr.com",
    phone: "+2348012345670",
    photo: "",
    jobTitle: "Legal Counsel",
    department: "Legal",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2025-01-15",
    supervisor: "Olufunke Adeyemi",
  },
  {
    id: "emp-011",
    employeeId: "SHR-2025-011",
    firstName: "Chibueze",
    lastName: "Okoro",
    email: "chibueze.okoro@sabihr.com",
    phone: "+2348023456780",
    photo: "",
    jobTitle: "Finance Director",
    department: "Finance",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2024-05-01",
    supervisor: "Olufunke Adeyemi",
  },
  {
    id: "emp-012",
    employeeId: "SHR-2025-012",
    firstName: "Ngozi",
    lastName: "Ibe",
    email: "ngozi.ibe@sabihr.com",
    phone: "+2348034567891",
    photo: "",
    jobTitle: "Sales Director",
    department: "Sales",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2024-07-01",
    supervisor: "Olufunke Adeyemi",
  },
  {
    id: "emp-013",
    employeeId: "SHR-2025-013",
    firstName: "Kemi",
    lastName: "Adekunle",
    email: "kemi.adekunle@sabihr.com",
    phone: "+2348045678902",
    photo: "",
    jobTitle: "Recruitment Specialist",
    department: "Human Resources",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "on-leave",
    startDate: "2025-06-01",
    supervisor: "Fatima Abdullahi",
  },
  {
    id: "emp-014",
    employeeId: "SHR-2025-014",
    firstName: "Damilola",
    lastName: "Osei",
    email: "damilola.osei@sabihr.com",
    phone: "+2348056789013",
    photo: "",
    jobTitle: "Frontend Developer",
    department: "Engineering",
    location: "Lagos Office",
    employmentType: "contract",
    employmentStatus: "active",
    startDate: "2025-09-01",
    supervisor: "Adebayo Ogunlesi",
  },
  {
    id: "emp-015",
    employeeId: "SHR-2025-015",
    firstName: "Usman",
    lastName: "Bello",
    email: "usman.bello@sabihr.com",
    phone: "+2348067890124",
    photo: "",
    jobTitle: "IT Support Technician",
    department: "IT",
    location: "Abuja Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2025-07-15",
    supervisor: "Ibrahim Musa",
  },
  {
    id: "emp-016",
    employeeId: "SHR-2025-016",
    firstName: "Amara",
    lastName: "Obi",
    email: "amara.obi@sabihr.com",
    phone: "+2348078901235",
    photo: "",
    jobTitle: "Content Marketing Specialist",
    department: "Marketing",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2025-08-01",
    supervisor: "Bukola Adeyemi",
  },
  {
    id: "emp-017",
    employeeId: "SHR-2025-017",
    firstName: "Olumide",
    lastName: "Fashola",
    email: "olumide.fashola@sabihr.com",
    phone: "+2348089012346",
    photo: "",
    jobTitle: "Account Executive",
    department: "Sales",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "suspended",
    startDate: "2025-03-15",
    supervisor: "Ngozi Ibe",
  },
  {
    id: "emp-018",
    employeeId: "SHR-2025-018",
    firstName: "Halima",
    lastName: "Yusuf",
    email: "halima.yusuf@sabihr.com",
    phone: "+2348090123457",
    photo: "",
    jobTitle: "Compliance Officer",
    department: "Legal",
    location: "Abuja Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2025-10-01",
    supervisor: "Yetunde Bakare",
  },
  {
    id: "emp-019",
    employeeId: "SHR-2025-019",
    firstName: "Segun",
    lastName: "Adeniyi",
    email: "segun.adeniyi@sabihr.com",
    phone: "+2348001234568",
    photo: "",
    jobTitle: "Operations Analyst",
    department: "Operations",
    location: "Lagos Office",
    employmentType: "intern",
    employmentStatus: "active",
    startDate: "2026-01-15",
    supervisor: "Ibrahim Musa",
  },
  {
    id: "emp-020",
    employeeId: "SHR-2025-020",
    firstName: "Folake",
    lastName: "Williams",
    email: "folake.williams@sabihr.com",
    phone: "+2348012345671",
    photo: "",
    jobTitle: "Payroll Specialist",
    department: "Finance",
    location: "Lagos Office",
    employmentType: "full-time",
    employmentStatus: "active",
    startDate: "2025-11-01",
    supervisor: "Chibueze Okoro",
  },
];
